# This workflow will upload a Python Package using Twine when a new commit to main is pushed
---
name: Python Continuous Deployment

on:  # yamllint disable-line rule:truthy
    push:
        branches: ["main"]

permissions:
    contents: read

jobs:
    deploy:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: '3.x'
            - name: Install dependencies
              run: |
                make bootstrap

            - name: Check if version was bumped
              run: |
                  published=$(curl -s https://pypi.org/pypi/infrahouse-toolkit/json | jq -r .info.version)
                  current=$(python -c "from infrahouse_toolkit import __version__; print(__version__)")
                  if [[ "$published" != "$current" ]]
                  then
                    echo "::set-env name=PUBLISH::yes"
                  else
                    echo "::set-env name=PUBLISH::no"
                  fi

            - name: Build package
              if: env.PUBLISH == 'yes'
              run: python -m build

            - name: Publish package
              if: env.PUBLISH == 'yes'
              uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
