---
name: OSV-Scanner PR Scan

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches: [main]
    merge_group:
        branches: [main]

permissions:
    contents: read
    pull-requests: write

env:
    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
    vulnerability-check:
        runs-on: ["self-hosted", "Linux", "noble"]
        steps:
            - name: Detect vulnerabilities
              run: |
                ih-github scan --repo ${{ github.repository }} --pull-request ${{ github.event.pull_request.number }}
