---
name: OSV-Scanner PR Scan

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches: [main]
    merge_group:
        branches: [main]

permissions:
    contents: read
    pull-requests: write

jobs:
    scan-pr:
    runs-on: ["self-hosted", "Linux", "noble"]
    steps:
        - name: Detect vulnerabilities
          run: |
              osv-scanner ./
